### ISSUE TITLE
Program crashes while reaching "reaching.go:80 Advance()" -> invalid memory address

### ISSUE THREAD

**Issue by infamousrev** [Arachnid/evmdis#1]
I found a small bug: I tried to use the program to disassemble the DarkDao-controlling-Proxy contract: 0xc0ee9db1a9e07ca63e4ff0d5fb6f86bf68d47b89

The program would crash with error: panic: runtime error: invalid memory address or nil pointer dereference

I narrowed down the problem to the fact that sometimes the program reaches reaching.go: Advance() , but self.nextBlock is no longer defined.

Adding a quickfix line of if(self.nextBlock == nil){return nil, nil;} seemed to have fixed the problem, and the contract disassembly seems complete*

*as far as I have seen so far.

**Comment by infamousrev** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x45d6fd]

goroutine 1 [running]:
github.com/arachnid/evmdis.(*reachingState).Advance(0xc2080d78a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/int/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/arachnid/evmdis/reaching.go:79 +0x6d
github.com/arachnid/evmdis.ExecuteAbstractly(0x7f8311419a30, 0xc20808dba0, 0x0, 0x0)
	/home/int/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/arachnid/evmdis/abstract.go:72 +0x16f
github.com/arachnid/evmdis.PerformReachingAnalysis(0xc20801e040, 0x0, 0x0)
	/home/int/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/arachnid/evmdis/reaching.go:59 +0xf8
main.main()
	/home/int/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/evmdis/evmdis/main.go:23 +0x24b

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:90
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/lib/golang/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/lib/golang/src/runtime/malloc.go:712
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

**Comment by Arachnid** [comment]
So, the problem here is 'throw', which gets compiled as a jump to an invalid address, which isn't in the jump table.

A complete fix requires both stopping execution at the point of the throw, as your patch does, and also patching the code that finds jump destinations to not worry about invalid ones, and fixing the output code to show 'throw' for any jump to an invalid destination.

I'll tackle this tomorrow morning.

**Comment by veox** [comment]
Was about to report failure on `throw` - @infamousrev, could you perhaps change the issue title if that's it?..

**Comment by Arachnid** [comment]
This is - finally - fixed.
