### ISSUE TITLE
Am I use evmdis only when I compile a contract ?

### ISSUE THREAD

**Issue by daichunkai** [Arachnid/evmdis#10]
Hello，I am confused about when and who use evmdis？Only the creator who creat the contract can use evmdis to disassemble contract when the creator compile the contrct？if I’m not the creator，and I only have the bytecode of a contract，can I use evmdis to disassemble bytecode and know how a contract run？

**Comment by Arachnid** [comment]
Anyone can use evmdis to disassemble contract bytecode.
