### ISSUE TITLE
A newcomer need a  detailed example

### ISSUE THREAD

**Issue by daichunkai** [Arachnid/evmdis#11]
After I downloaded evmdis, I don't how to configure the environment and use it. If I got the bytecode "0x606060405260388060106000396000f3606060405260e060020a6000350463c6888fa18114601c575b6002565b3460025760076004350260408051918252519081900360200190f3". What should I do to analysis it with evmdis? Can you help me list the detailed steps?Thank you very much!

**Comment by shoenseiwaso** [comment]
Hi @daichunkai, I'm not the maintainer but we wrote a blog post that might help you get started with evmdis:
http://blog.curvegrid.com/daysofblock/2017/05/11/daysofblock-01-evmdis.html

**Comment by shoenseiwaso** [comment]
Here's a simple example with your particular bytestream. Note that:
- You need to remove the leading base-16 indicator, 0x.
- Ensure there are no trailing newlines (-n option to echo).
- This looks like a solidity loader wrapper, where what you probably want is the smart contract itself. Try recompiling with --bin-runtime (if using solc).

```bash
$ echo -n "606060405260388060106000396000f3606060405260e060020a6000350463c6888fa18114601c575b6002565b3460025760076004350260408051918252519081900360200190f3" | evmdis
2017/06/15 11:06:22 Entering block at 0 with stack height 0
# Stack: []
0x4	MSTORE(0x40, 0x60)
0x5	PUSH(0x38)
0x7	DUP1
0xC	CODECOPY(0x0, 0x10, POP())
0xF	RETURN(0x0, POP())
```

**Comment by daichunkai** [comment]
Thank you very much for your help!

**Comment by daichunkai** [comment]
@shoenseiwaso   Thank you very much for your help!
