### ISSUE TITLE
Disassembler loops forever with this bytecode

### ISSUE THREAD

**Issue by mattdf** [Arachnid/evmdis#2]
When trying to disassemble the following:

60006014525b600a601451101561001c5760016001601451016014525b600a60145110156100055700

The tool seems to loop forever. This runs fine if fed to "./evm --code".

Any ideas? From a quick glance, it seems like there may be an issue with the forward reference in for the JUMP :label creation.

**Comment by Arachnid** [comment]
Fixed:

```
# Stack: []
0x4	MSTORE(0x14, 0x0)

:label0
# Stack: []
0x10	JUMPI(:label1, !(MLOAD(0x14) < 0xA))

# Stack: []
0x11	PUSH(0x1)
0x1B	MSTORE(0x14, MLOAD(0x14) + 0x1)

:label1
# Stack: []
0x27	JUMPI(:label0, !(MLOAD(0x14) < 0xA))

# Stack: []
0x28	STOP()

```
