### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by wighawag** [Arachnid/evmdis#21]
After installing evmdis, when I execute it via (or any other way actually)

```
evmdis -h
```

I get the following message in stdout:

```
Illegal instruction
```

I am on android using GNURootDebian. (not sure if is part of the problem)

any idea? (can't find any reference to that message in the source code

**Comment by shoenseiwaso** [comment]
Hi @wighawah, can you provide more information on the steps you took to download and compile evmdis?

For example, `go get` with specific cross-compiler flags. Also, please include your golang version.

**Comment by wighawag** [comment]
Hi @shoenseiwaso

I initially cloned the repo in the correct GOPATH/src location, and executed  go build
Then because of the issue I executed go install ...

My go version is actually very old, maybe that is the issue : 1.3.3 

I tried to install the latest go version 1.9.1 without success. Might be a incompatible glibc

**Comment by wighawag** [comment]
No flag was added

**Comment by shoenseiwaso** [comment]
1.3.3 is quite an old version of Go, can you try upgrading? A quick web search turned up some issues with older Go versions that might be related.

More generally, the error message could imply you are compiling for one CPU architecture, but attempting to run it on another. For example, you're compiling on your laptop which is an x86 CPU but running it on Android which is an ARM CPU. Do you think this might be the case?

**Comment by wighawag** [comment]
I am building from proper architecture, everything is done on the same device

I upgraded to 1.7 and now I got a different error :

```
go install github.com/Arachnid/evmdis/evmdis
```
Result in:
```
go build github.com/Arachnid/evmdis/stack: /usr/lib/go-1.7/pkg/tool/linux_arm/compile: signal: segmentation fault
```

**Comment by shoenseiwaso** [comment]
That looks like a compiler issue: either a bug in Go 1.7, or an issue on your platform. I tried cross-compiling for Linux on ARM with Go 1.7 but couldn't reproduce the particular issue:
```
$ GOROOT=`pwd`/tmp/go tmp/go/bin/go version
go version go1.7 darwin/amd64
$ GOOS=linux GOARCH=arm GOROOT=`pwd`/tmp/go tmp/go/bin/go build -o ./evmdis-arm-test github.com/Arachnid/evmdis/evmdis
$
```

You could try [opening an issue](https://github.com/golang/go/issues) with the Go team directly, but I suspect their response is going to be, "upgrade to the latest version of Go".

Do you have any other ideas about what it might be?

Regardless, I don't think it's related to evmdis. For example, here are all the imports:
```
$ find * -iname '*.go' | xargs -I{} grep -C 6 import {} | grep -E '"' | sort -u
	"encoding/hex"
	"flag"
	"fmt"
	"github.com/Arachnid/evmdis/stack"
	"io/ioutil"
	"log"
	"math/big"
	"os"
	"reflect"
	"strings"
```

**Comment by wighawag** [comment]
Thanks @shoenseiwaso for your time, this indeed does not seem to be a evmdis issue. 
I ll close it and add a comment if I find a solution
