### ISSUE TITLE
Can't install EVMDIS on Ubuntu 20.04 virtual machine

### ISSUE THREAD

**Issue by zak100** [Arachnid/evmdis#25]
Hi,
I tried the following:
osboxes@osboxes:~$ go get github.com/Arachnid/evmdis
osboxes@osboxes:~$ go install github.com/Arachnid/evmdis/evmdis
osboxes@osboxes:~$ which evmdis
osboxes@osboxes:~$

osboxes@osboxes:~$ evmdis
evmdis: command not found
osboxes@osboxes:~$ whereis evmdis
evmdis:
osboxes@osboxes:~$ 

Please guide me how to install evmdis?

Zulfi.

**Comment by Arachnid** [comment]
I'm sorry, evmdis is way out of date, and unsupported.
